#ifndef CONTROLLER_H
#define CONTROLLER_H

#include <cstdint>

// defines all control signals generated by the controller.
struct ControlSignals {
    bool RegWrite;
    bool MemRead;
    bool MemWrite;
    bool Branch; 
    bool ALUSrc;
    bool MemtoReg;
    uint8_t ALUOp; // 2-bit signal for the ALU Controller
    bool LUISel;   // Select immediate instead of ALU result for LUI
    bool JALRSel;  // Select PC+4 for writeback (for JALR)
    uint8_t PCSrc; // PC source: 0=PC+4, 1=PC+imm(branch), 2=rs1+imm(JALR)
};

enum opCodes
{
    RTYPE = 0b0110011,
    ITYPE = 0b0010011,
    LW = 0b0000011,
    SW = 0b0100011,
	LUI = 0b0110111,
    BNE = 0b1100011,
    JALR = 0b1100111,
};

class Controller {
public:
    // Control logic.
    ControlSignals generate_signals(uint8_t opcode);

    // ALU Control logic.
    uint8_t aluController(uint8_t opcode, uint8_t funct3, uint8_t funct7, uint8_t alu_op);
};

#endif // CONTROLLER_H
